---
name: ci

on:
  pull_request:
    branches:
      - master
      - main
      - develop
  push:
    branches:
      - master
      - main
      - develop
  workflow_dispatch:
    inputs:
      bottles_artifact_data:
        description: "JSON string with artifact details from test-bot to install & test"
        required: true
        type: string

env:
  debug_ci: true
jobs:
  bottles-artifact:
    runs-on: ubuntu-latest
    outputs:
      bottles_artifact_data: ${{ steps.set-data.outputs.bottles_artifact_data || steps.import-artifact-data.outputs.bottles_artifact_data }}
    steps:
      - name: Set outputs from workflow dispatch inputs
        id: set-data
        run: |
          echo 'bottles_artifact_data=${{ github.event.inputs.bottles_artifact_data }}' >> "$GITHUB_OUTPUT"
        if: ${{ github.event.inputs.bottles_artifact_data != '' }}
      - name: Get run-id from workflow_dispatch input data
        uses: actions/github-script@v8
        if: ${{ github.event.inputs.bottles_artifact_data != '' }}
        id: import-artifact-data-input
        env:
          BOTTLES_ARTIFACT_DATA: ${{ steps.set-data.outputs.bottles_artifact_data }}
        with:
          script: |
            const inputData = JSON.parse(process.env.BOTTLES_ARTIFACT_DATA || '{}');
            try {
              core.setOutput('run-id', inputData[Object.keys(inputData)[0]].workflow_run_id || '');
              core.summary.addHeading('Bottles Artifact Data', '2');
              core.summary.addBreak();
              core.summary.addRaw(`**Using \`workflow_run_id\` from \`workflow_dispatch\` input data:** ${inputData[Object.keys(inputData)[0]].workflow_run_id || ''}\n`);
            } catch (err) {
              core.error(`\u001b[1m\u001b[38;5;1mError:\u001b[0m Error reading \u001b[38;5;6mworkflow_run_id\u001b[0m from \u001b[38;5;6mbottles_artifact_data\u001b[0m JSON input: \u001b[38;5;9m${err.message}\u001b[0m`);
            } finally {
              core.summary.write();
            }
      - name: DEBUG - Print refs
        if: ${{ env.debug_ci == 'true' }}
        run: |
          echo '${{ github.ref }}'
      - name: Wait for tests to succeed
        if: ${{ github.event.inputs.bottles_artifact_data == '' }}
        uses: lewagon/wait-on-check-action@v1.4.0
        with:
          ref: ${{ github.ref }}
          check-name: 'trigger_artifact_test'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 10
      - name: Get run ID of "tests.yml" workflow
        id: tests-workflow
        if: ${{ github.event.inputs.bottles_artifact_data == '' }}
        run: |
          REPO="${{ github.repository }}"
          WF_NAME="tests.yml"
          RUN_ID="$(gh run --repo "${REPO}" list --workflow "${WF_NAME}" --json databaseId --jq '.[0].databaseId')"
          echo "Detected latest run id of ${RUN_ID} for workflow ${WF_NAME}"
          echo "run-id=${RUN_ID}" >> "$GITHUB_OUTPUT"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/download-artifact@v5
        id: download-artifact-metadata
        if: ${{ github.event.inputs.bottles_artifact_data == '' }}
        with:
          pattern: 'bottles-metadata.json'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          run-id: ${{ steps.import-artifact-data-input.outputs.run-id || steps.tests-workflow.outputs.run-id }}
          path: "${GITHUB_WORKSPACE}/bottles-artifact"
      - name: DEBUG - Artifact bottles-metadata.json contents
        if: ${{ env.debug_ci == 'true' && github.event.inputs.bottles_artifact_data == '' }}
        run: |
          ls -R ${{ steps.download-artifact-metadata.outputs.download-path }}
          cat "${GITHUB_WORKSPACE}/bottles-artifact/bottles-metadata.json" || true
      - uses: actions/github-script@v8
        if: ${{ github.event.inputs.bottles_artifact_data == '' }}
        id: import-artifact-data
        env:
          BOTTLES_ARTIFACT_DATA_JSON_FILE: ${{ steps.download-artifact-metadata.outputs.download-path }}/bottles-metadata.json
        with:
          script: |
            const fs = require('node:fs');
            const inputDataFile = process.env.BOTTLES_ARTIFACT_DATA_JSON_FILE;
            let inputData = {};
            try {
              inputData = JSON.parse(fs.readFileSync(inputDataFile, 'utf8'));
              core.setOutput('bottles_artifact_data', JSON.stringify(inputData));
            } catch (err) {
              console.log(`Errror reading data from artifact metadata JSON file: ${err}`);
            }

  test:
    needs: bottles-artifact
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
      - name: Get artifact data for current OS
        uses: actions/github-script@v8
        id: artifact-data
        env:
          BOTTLES_ARTIFACT_DATA: ${{ needs.bottles-artifact.outputs.bottles_artifact_data }}
          OS: ${{ matrix.os }}
        with:
          script: |
            const inputData = JSON.parse(process.env.BOTTLES_ARTIFACT_DATA || '{}');
            const os = process.env.OS || '';
            try {
              if (Object.keys(inputData).length === 0) {
                console.log('No bottles artifact data provided as workflow_dispatch input.');
                console.log('Checking for artifact metadata JSON file...');
                core.warning(`\u001b[1m\u001b[38;5;3mWarning:\u001b[0m \u001b[38;5;9mNo bottles artifact data provided as workflow_dispatch input.\u001b[0m`);
              } else {
                inputDataKeys = Object.keys(inputData);
                console.log(`Found bottles artifact data for: ${inputDataKeys.join(', ')}`);
                if (inputData[os]) {
                  console.log(`Using artifact data for current OS: ${os}`);
                  core.setOutput('id', inputData[os].id || '');
                  core.setOutput('url', inputData[os].url || '');
                  core.setOutput('digest', inputData[os].digest || '');
                  core.setOutput('arch', inputData[os].arch || '');
                  core.notice(`\u001b[1m\u001b[38;5;6mArtifact Data:\u001b[0m \u001b[38;5;2m${os}\u001b[0m => ${JSON.stringify(inputData[os], null, 2)}`);
                } else {
                  core.error(`\u001b[1m\u001b[38;5;1mError:\u001b[0m : \u001b[38;5;9mNo artifact data found for current OS:\u001b[0m \u001b[38;5;6m${os}\u001b[0m`);
                }
              }
            } finally {
              core.summary.write();
            }
# Now handled by Homebrew/actions/setup-homebrew
# See: https://github.com/Homebrew/actions/blob/master/setup-homebrew/main.sh#L207-L242
#      - name: Check out code
#        uses: actions/checkout@v4
      - uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Add SSH_AUTH_SOCK to user shell .profile
        run: |
          sudo tee -a ~/.profile <<EOPROFILE
          SSH_AUTH_SOCK=${{ env.SSH_AUTH_SOCK }}
          EOPROFILE
      - name: Configure global git SSH URLs
        run: |
          git config --global url."git@github.com:".insteadOf "https://github.com/"

      - name: Set BREWFILE_PATH env var
        run: |
          echo "BREWFILE_PATH=${GITHUB_WORKSPACE}/Brewfile.ci" >> "$GITHUB_ENV"

      - name: DEBUG - Print all shell env exports
        run: export -p
        if: ${{ env.debug_ci == 'true' }}

      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@master

      - name: Check out Pull Request
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: DEBUG Tap Repo
        run: |
          echo HOMEBREW_TAP_REPOSITORY=${{ steps.set-up-homebrew.outputs.repository-path }}
          ls -l ${{ steps.set-up-homebrew.outputs.repository-path }}
          cd ${{ steps.set-up-homebrew.outputs.repository-path }} && git status && git log --graph --decorate --oneline --all --abbrev-commit
        if: ${{ env.debug_ci == 'true' }}

      - name: Cache Homebrew Bundler RubyGems
        id: cache
        uses: actions/cache@v4
        with:
          path: ${{ steps.set-up-homebrew.outputs.gems-path }}
          key: ${{ matrix.os }}-${{ runner.os }}-${{ runner.arch }}-rubygems-${{ steps.set-up-homebrew.outputs.gems-hash }}
          restore-keys: ${{ matrix.os }}-${{ runner.os }}-${{ runner.arch }}-rubygems-

      - name: Cache style cache
        if: runner.os == 'macOS'
        uses: actions/cache@v4
        with:
          path: ~/Library/Caches/Homebrew/style
          key: macos-style-cache-${{ github.sha }}
          restore-keys: macos-style-cache-

      - name: Cache local Tap Casks
        if: runner.os == 'macOS'
        uses: actions/cache@v4
        with:
          path: |
            ~/Library/Caches/Homebrew/Cask/vmware-fusion@13.5.2--*
            ~/Library/Caches/Homebrew/downloads/*--com.vmware.fusion.zip.tar*
            ~/Library/Caches/Homebrew/downloads/*--machine-*.tar.gz*
          key: brew-${{ matrix.os }}-${{ runner.os }}-${{ runner.arch }}-${{ hashFiles('.github/clear_github_actions_cache') }}-${{ hashFiles( env.BREWFILE_PATH, '**/Brewfile.lock.json') }}-${{ hashFiles('Casks/**.rb') }}
          restore-keys: |
            brew-${{ matrix.os }}-${{ runner.os }}-${{ runner.arch }}-${{ hashFiles('.github/clear_github_actions_cache') }}-${{ hashFiles( env.BREWFILE_PATH, '**/Brewfile.lock.json') }}-${{ hashFiles('Casks/**.rb') }}
            brew-${{ matrix.os }}-${{ runner.os }}-${{ runner.arch }}-${{ hashFiles('.github/clear_github_actions_cache') }}-${{ hashFiles( env.BREWFILE_PATH, '**/Brewfile.lock.json') }}
            brew-${{ matrix.os }}-${{ runner.os }}-${{ runner.arch }}-${{ hashFiles('.github/clear_github_actions_cache') }}

      # Note: Disabling this b/c size is over 3 GiB now!
      # So, cache was actually slowing down the CI run
      # - name: Configure Homebrew cache
      #   uses: actions/cache@v4
      #   with:
      #     path: |
      #       ~/Library/Caches/Homebrew/*--*
      #       ~/Library/Caches/Homebrew/downloads/*--*
      #       ~/Library/Caches/Homebrew/Cask/*--*
      #     key: brew-${{ matrix.os }}-${{ runner.os }}-${{ runner.arch }}-${{ hashFiles('.github/clear_github_actions_cache') }}-${{ hashFiles( env.BREWFILE_PATH, '**/Brewfile.lock.json') }}
      #     restore-keys: |
      #       brew-${{ matrix.os }}-${{ runner.os }}-${{ runner.arch }}-${{ hashFiles('.github/clear_github_actions_cache') }}-${{ hashFiles( env.BREWFILE_PATH, '**/Brewfile.lock.json') }}
      #       brew-${{ matrix.os }}-${{ runner.os }}-${{ runner.arch }}-${{ hashFiles('.github/clear_github_actions_cache') }}

      - name: Run brew update
        env:
          HOMEBREW_COLOR: 1
          HOMEBREW_DEVELOPER: 1
        run: |
          brew update-reset
      - name: Fix Tap repo checked out merge commit ref (post brew update-reset)
        run: |
          cd '${{ steps.set-up-homebrew.outputs.repository-path }}' && git checkout "refs/remotes/pull/${GITHUB_REF_NAME}"
        if: github.ref != 'refs/heads/main' && github.event_name == 'pull_request'
      - name: Clean homebrew cache
        env:
          HOMEBREW_COLOR: 1
          HOMEBREW_DEVELOPER: 1
        run: |
          brew cleanup

      - name: Login to GitHub Packages repo (docker v2 API)
        id: ghcr_login
        env:
          HOMEBREW_COLOR: 1
          HOMEBREW_DEVELOPER: 1
          LYRAPHASE_RUNNER_PACKAGES_GHCR_USER: "${{ secrets.LYRAPHASE_RUNNER_PACKAGES_GHCR_USER }}"
          LYRAPHASE_RUNNER_PACKAGES_GHCR_CLASSIC_TOKEN: "${{ secrets.LYRAPHASE_RUNNER_PACKAGES_GHCR_CLASSIC_TOKEN }}"
        run: |
          brew install jq || true
          if [ "macOS" == "$RUNNER_OS" ]; then
            base64_flags='-b 0 -o -'
          elif [ "Linux" == "$RUNNER_OS" ]; then
            base64_flags='-w 0'
          fi
          # shellcheck disable=SC2086
          GHCR_BASIC_AUTH_TOKEN="$(echo -n "${LYRAPHASE_RUNNER_PACKAGES_GHCR_USER}:${LYRAPHASE_RUNNER_PACKAGES_GHCR_CLASSIC_TOKEN}" | base64 $base64_flags )"
          GHCR_TOKEN="$(curl -o - -v -H "Authorization: Basic ${GHCR_BASIC_AUTH_TOKEN}" \
            "https://ghcr.io/token?service=ghcr.io&scope=repository:${GITHUB_REPOSITORY_OWNER}/${GITHUB_REPOSITORY##*/homebrew-}/*:pull" | \
            jq -jr '.token')"
          if [ -n "$GHCR_TOKEN" ]; then
            echo "ghcr_bearer_token=${GHCR_TOKEN}" >> "${GITHUB_OUTPUT}"
          fi
          if [ -n "$GHCR_BASIC_AUTH_TOKEN" ]; then
            echo "ghcr_basic_token=${GHCR_BASIC_AUTH_TOKEN}" >> "${GITHUB_OUTPUT}"
          fi
          :

      - name: DEBUG - Show artifact details if passed
        run: |
          echo 'bottles_artifact_data=${{ needs.bottles-artifact.outputs.bottles_artifact_data }}'
        if: ${{ env.debug_ci == 'true' && needs.bottles-artifact.outputs.bottles_artifact_data != '' }}
      - name: Download artifact
        id: download_artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ steps.artifact-data.outputs.id }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          run-id: ${{ steps.artifact-data.outputs.workflow_run_id }}
        if: ${{ steps.artifact-data.outputs.id != '' && steps.artifact-data.outputs.workflow_run_id != '' }}
      - name: DEBUG - List downloaded artifact files
        run: |
          ls -lA "${GITHUB_WORKSPACE}/"
          ls -lA "${GITHUB_WORKSPACE}/${{ steps.download_artifact.outputs.download-path }}"
          ls -lA ${{ steps.download_artifact.outputs.download-path }}/
        if: ${{ env.debug_ci == 'true' && steps.download_artifact.outputs.download-path != '' }}
      - name: HACK - Force link conflicting go binaries
        env:
          HOMEBREW_COLOR: 1
          HOMEBREW_DEVELOPER: 1
          HOMEBREW_BOTTLE_DOMAIN: 'https://ghcr.io/v2/LyraPhase/right2repair'
          HOMEBREW_GITHUB_PACKAGES_USER: "${{ secrets.LYRAPHASE_RUNNER_PACKAGES_GHCR_USER }}"
          HOMEBREW_DOCKER_REGISTRY_BASIC_AUTH_TOKEN: "${{ steps.ghcr_login.outputs.ghcr_basic_token }}"
          HOMEBREW_DOCKER_REGISTRY_TOKEN: "${{ steps.ghcr_login.outputs.ghcr_bearer_token }}"
        run: |
          if [ -e "/usr/local/opt/go@1.21" ]; then
            brew install go || true
            brew link --overwrite go
          fi
          :

      - name: Install Brewfile.ci dependencies
        env:
          HOMEBREW_COLOR: 1
          HOMEBREW_DEVELOPER: 1
          HOMEBREW_BOTTLE_DOMAIN: 'https://ghcr.io/v2/LyraPhase/right2repair'
          HOMEBREW_GITHUB_PACKAGES_USER: "${{ secrets.LYRAPHASE_RUNNER_PACKAGES_GHCR_USER }}"
          HOMEBREW_DOCKER_REGISTRY_BASIC_AUTH_TOKEN: "${{ steps.ghcr_login.outputs.ghcr_basic_token }}"
          HOMEBREW_DOCKER_REGISTRY_TOKEN: "${{ steps.ghcr_login.outputs.ghcr_bearer_token }}"
          HOMEBREW_ALLOWED_TAPS: 'lyraphase/right2repair'
          HOMEBREW_FORBIDDEN_TAPS: 'homebrew/core'
        run: |
          brew bundle install --file="${BREWFILE_PATH}"

      - name: DEBUG - GitHub Workspace
        run: |
          echo GITHUB_WORKSPACE="$GITHUB_WORKSPACE"
        if: ${{ env.debug_ci == 'true' }}
      - name: DEBUG - Print all shell env exports
        run: export -p
        if: ${{ env.debug_ci == 'true' }}
      - name: DEBUG - List workspace and Homebrew contents
        run: |
          ls -lR "${GITHUB_WORKSPACE}"
          ls -lR "$(brew --prefix)"
        if: ${{ env.debug_ci == 'true' }}
      - name: Run test setup
        env:
          HOMEBREW_COLOR: 1
          HOMEBREW_DEVELOPER: 1
          HOMEBREW_NO_SORBET_RUNTIME: 1
        run: make test-before || true
      - name: Run tap install
        env:
          HOMEBREW_COLOR: 1
          HOMEBREW_DEVELOPER: 1
          HOMEBREW_NO_SORBET_RUNTIME: 1
        run: make install
      - name: Run test & install
        env:
          HOMEBREW_COLOR: 1
          HOMEBREW_DEVELOPER: 1
          HOMEBREW_DISPLAY_INSTALL_TIMES: 1
          HOMEBREW_BOTTLE_DOMAIN: 'https://ghcr.io/v2/LyraPhase/right2repair'
          HOMEBREW_GITHUB_PACKAGES_USER: "${{ secrets.LYRAPHASE_RUNNER_PACKAGES_GHCR_USER }}"
          HOMEBREW_DOCKER_REGISTRY_BASIC_AUTH_TOKEN: "${{ steps.ghcr_login.outputs.ghcr_basic_token }}"
          HOMEBREW_DOCKER_REGISTRY_TOKEN: "${{ steps.ghcr_login.outputs.ghcr_bearer_token }}"
        run: |
          make test
      - name: Upload install.log on failure
        if: ${{ failure() }}
        uses: actions/upload-artifact@v4
        with:
          name: Build failure logs
          path: /var/log/install.log
      - name: Cleanup & teardown after test
        if: always()
        env:
          HOMEBREW_COLOR: 1
          HOMEBREW_DEVELOPER: 1
          HOMEBREW_DISPLAY_INSTALL_TIMES: 1
        run: |
          make test-clean
