name: brew test-bot
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  test-bot:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-12, macos-13, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@master

      - name: Cache Homebrew Bundler RubyGems
        id: cache
        uses: actions/cache@v4
        with:
          path: ${{ steps.set-up-homebrew.outputs.gems-path }}
          key: ${{ matrix.os }}-${{ runner.os }}-rubygems-${{ steps.set-up-homebrew.outputs.gems-hash }}
          restore-keys: ${{ matrix.os }}-${{ runner.os }}-rubygems-

      - name: Install Homebrew Bundler RubyGems
        if: steps.cache.outputs.cache-hit != 'true'
        run: brew install-bundler-gems

      - name: Set BREWFILE_PATH env var
        run: |
          echo "BREWFILE_PATH=${GITHUB_WORKSPACE}/Brewfile.ci" >> "$GITHUB_ENV"

      - name: HACK - Bottle go + Force link conflicting go binaries
        env:
          HOMEBREW_COLOR: 1
          HOMEBREW_DEVELOPER: 1
        run: |
          if [ -e "/usr/local/opt/go@1.21" ]; then
            brew install --build-bottle go || true
            brew link --overwrite go
            brew bottle go
          fi
          :

      - name: Install Brewfile.ci dependencies
        env:
          HOMEBREW_COLOR: 1
          HOMEBREW_DEVELOPER: 1
        run: |
          brew bundle install --file="${BREWFILE_PATH}"

      - run: brew test-bot --only-cleanup-before

      - run: brew test-bot --only-setup

      # Allow our own tap style overrides
      - run: |
          sed -i'' -e '/Style\/DisableCopsWithinSourceCodeDirective:/{n;s/.*Enabled: true/  Enabled: false/;}' "$(brew --repository)"/Library/.rubocop.yml

      - run: brew test-bot --only-tap-syntax

      - run: brew test-bot --only-formulae
        if: github.event_name == 'pull_request'

      - name: DEBUG - bottle files
        run: ls -lA ./*bottle*
        if: github.event_name == 'pull_request'

      - name: Upload bottles as artifact
        if: always() && github.event_name == 'pull_request'
        uses: actions/upload-artifact@main
        with:
          name: bottles-${{ matrix.os }}-${{ runner.arch }}
          path: '*.bottle.*'
