name: brew test-bot
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  setup-matrix:
    env:
      # MATRIX_OS_LIST: '["ubuntu-latest", "self-hosted-macos-12", "macos-13", "macos-14", "macos-latest"]'
      MATRIX_OS_LIST: '["ubuntu-latest", "macos-latest"]'
    runs-on: ubuntu-latest
    outputs:
      os_list: ${{ steps.set-matrix.outputs.os_list }}
      dispatch_ref: ${{ github.event.pull_request.head.ref || false }}
    steps:
      - name: Define matrix OS list
        id: set-matrix
        run: |
          echo MATRIX_OS_LIST is "${MATRIX_OS_LIST}"
          echo 'os_list=${{ env.MATRIX_OS_LIST }}' >> "$GITHUB_OUTPUT"
  test-bot:
    needs: setup-matrix
    outputs:
      artifact_ubuntu-latest: ${{ steps.artifact-dict.outputs.artifact_ubuntu-latest }}
      artifact_self-hosted-macos-12: ${{ steps.artifact-dict.outputs.artifact_self-hosted-macos-12 }}
      artifact_macos-13: ${{ steps.artifact-dict.outputs.artifact_macos-13 }}
      artifact_macos-14: ${{ steps.artifact-dict.outputs.artifact_macos-14 }}
      artifact_macos-latest: ${{ steps.artifact-dict.outputs.artifact_macos-latest }}
    strategy:
      matrix:
        os: ${{ fromJSON(needs.setup-matrix.outputs.os_list) }}
    runs-on: ${{ matrix.os }}
    steps:
      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@master

      - name: Cache Homebrew Bundler RubyGems
        id: cache
        uses: actions/cache@v4
        with:
          path: ${{ steps.set-up-homebrew.outputs.gems-path }}
          key: ${{ matrix.os }}-${{ runner.os }}-rubygems-${{ steps.set-up-homebrew.outputs.gems-hash }}
          restore-keys: ${{ matrix.os }}-${{ runner.os }}-rubygems-

      - name: Install Homebrew Bundler RubyGems
        if: steps.cache.outputs.cache-hit != 'true'
        run: brew install-bundler-gems

      - name: Set BREWFILE_PATH env var
        run: |
          echo "BREWFILE_PATH=${GITHUB_WORKSPACE}/Brewfile.ci" >> "$GITHUB_ENV"

      - name: Create brewed-bottles dir
        run: |
          mkdir "${RUNNER_TEMP}/brewed-bottles"
          pwd
          ls -lA "${RUNNER_TEMP}/brewed-bottles"

      - name: HACK - Bottle go + Force link conflicting go binaries
        env:
          HOMEBREW_COLOR: 1
          HOMEBREW_DEVELOPER: 1
        run: |
          if [ -e "/usr/local/opt/go@1.21" ]; then
            brew install --build-bottle go || true
            brew link --overwrite go
            brew bottle go
            # find "${GITHUB_WORKSPACE}" -iname '*.bottle.*' -exec mv '{}' "${RUNNER_TEMP}/brewed-bottles/" \;
            ls -l "${RUNNER_TEMP}/brewed-bottles/"
          fi
          :

      - name: Login to GitHub Packages repo (docker v2 API)
        id: ghcr_login
        env:
          HOMEBREW_COLOR: 1
          HOMEBREW_DEVELOPER: 1
          LYRAPHASE_RUNNER_PACKAGES_GHCR_USER: "${{ secrets.LYRAPHASE_RUNNER_PACKAGES_GHCR_USER }}"
          LYRAPHASE_RUNNER_PACKAGES_GHCR_CLASSIC_TOKEN: "${{ secrets.LYRAPHASE_RUNNER_PACKAGES_GHCR_CLASSIC_TOKEN }}"
        run: |
          brew install jq || true
          if [ "macOS" == "$RUNNER_OS" ]; then
            base64_flags='-b 0 -o -'
          elif [ "Linux" == "$RUNNER_OS" ]; then
            base64_flags='-w 0'
          fi
          # shellcheck disable=SC2086
          GHCR_BASIC_AUTH_TOKEN="$(echo -n "${LYRAPHASE_RUNNER_PACKAGES_GHCR_USER}:${LYRAPHASE_RUNNER_PACKAGES_GHCR_CLASSIC_TOKEN}" | base64 $base64_flags )"
          GHCR_TOKEN="$(curl -o - -v -H "Authorization: Basic ${GHCR_BASIC_AUTH_TOKEN}" \
            "https://ghcr.io/token?service=ghcr.io&scope=repository:${GITHUB_REPOSITORY_OWNER}/${GITHUB_REPOSITORY##*/homebrew-}/*:pull" | \
            jq -jr '.token')"
          if [ -n "$GHCR_TOKEN" ]; then
            echo "ghcr_bearer_token=${GHCR_TOKEN}" >> "${GITHUB_OUTPUT}"
          fi
          if [ -n "$GHCR_BASIC_AUTH_TOKEN" ]; then
            echo "ghcr_basic_token=${GHCR_BASIC_AUTH_TOKEN}" >> "${GITHUB_OUTPUT}"
          fi
          :

      - name: Install Brewfile.ci dependencies
        env:
          HOMEBREW_COLOR: 1
          HOMEBREW_DEVELOPER: 1
          HOMEBREW_BOTTLE_DOMAIN: 'https://ghcr.io/v2/LyraPhase/right2repair'
          HOMEBREW_GITHUB_PACKAGES_USER: "${{ secrets.LYRAPHASE_RUNNER_PACKAGES_GHCR_USER }}"
          HOMEBREW_DOCKER_REGISTRY_BASIC_AUTH_TOKEN: "${{ steps.ghcr_login.outputs.ghcr_basic_token }}"
          HOMEBREW_DOCKER_REGISTRY_TOKEN: "${{ steps.ghcr_login.outputs.ghcr_bearer_token }}"
          HOMEBREW_ALLOWED_TAPS: 'lyraphase/right2repair'
          HOMEBREW_FORBIDDEN_TAPS: 'homebrew/core'
        run: |
          brew bundle install --file="${BREWFILE_PATH}"

      - run: brew test-bot --only-cleanup-before

      - run: brew test-bot --only-setup

      # Allow our own tap style overrides
      - run: |
          sed -i'' -e '/Style\/DisableCopsWithinSourceCodeDirective:/{n;s/.*Enabled: true/  Enabled: false/;}' "$(brew --repository)"/Library/.rubocop.yml

      - run: brew test-bot --only-tap-syntax

      - run: |
          brew test-bot --only-formulae --only-json-tab --skip-recursive-dependents --root-url="https://ghcr.io/v2/LyraPhase/right2repair"
        if: github.event_name == 'pull_request'

      - name: Move bottle files
        run: |
          find "${GITHUB_WORKSPACE}" -iname '*.bottle.*' -exec mv '{}' "${RUNNER_TEMP}/brewed-bottles/" \;
          ls -lA "${RUNNER_TEMP}/brewed-bottles/"
        if: github.event_name == 'pull_request'

      - name: Upload bottles as artifact
        id: upload-bottles
        if: always() && github.event_name == 'pull_request'
        uses: actions/upload-artifact@main
        with:
          name: bottles_${{ matrix.os }}-${{ runner.arch }}
          path: '${{ runner.temp }}/brewed-bottles/*.bottle.*'
      - name: HACK - Set per-os matrix Bottle artifact ID Output
        id: artifact-dict
        uses: actions/github-script@v7
        env:
          GITHUB_JOB_ID: "${{ github.run_number }}-${{ github.run_attempt }}"
          BOTTLES_ARTIFACT_ID: "${{ steps.upload-bottles.outputs.artifact-id }}"
          BOTTLES_ARTIFACT_URL: "${{ steps.upload-bottles.outputs.artifact-url }}"
          BOTTLES_ARTIFACT_DIGEST: "${{ steps.upload-bottles.outputs.artifact-digest }}"
          OS: "${{ matrix.os }}"
          ARCH: "${{ runner.arch }}"
        with:
          script: |
            if (core.isDebug()) {
              console.log('context:', context);
            }
            const bottlesArtifactID = process.env.BOTTLES_ARTIFACT_ID;
            const bottlesArtifactURL = process.env.BOTTLES_ARTIFACT_URL;
            const bottlesArtifactDigest = process.env.BOTTLES_ARTIFACT_DIGEST;
            const githubJobID = process.env.GITHUB_JOB_ID;
            const os = process.env.OS;
            const arch = process.env.ARCH;
            const outputValue = {
              ref: context.ref,
              os: os,
              arch: arch,
              id: bottlesArtifactID,
              url: bottlesArtifactURL,
              digest: bottlesArtifactDigest,
              job_id: githubJobID,
              workflow_run_id: context.runId
            };
            const outputKey = `artifact_${os}`;
            core.setOutput(outputKey, JSON.stringify(outputValue));
          result-encoding: string
  autoreview-check:
    needs: test-bot
    runs-on: ubuntu-latest
    steps:
      - name: Check triggering user permissions
        id: check_user_permissions
        uses: actions-cool/check-user-permission@v2.3.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          username: ${{ github.triggering_actor }}
          require: admin
    outputs:
      authorized: ${{ steps.check_user_permissions.outputs.require-result }}
  autoreview:
    if: format('{0}', needs.autoreview-check.outputs.authorized) == 'true' && github.event_name == 'pull_request' && github.event.pull_request.merged != true
    needs: [test-bot, autoreview-check]
    runs-on: ubuntu-latest
    env:
      PR: ${{ github.event.pull_request.number }}
    steps:
      - name: Auto-approve review for admins
        env:
          GH_TOKEN: ${{ secrets.LYRAPHASE_RUNNER_PACKAGES_TOKEN }}
        run: |
          pr_data="$(
            gh api \
              --header 'Accept: application/vnd.github+json' \
              --header 'X-GitHub-Api-Version: 2022-11-28' \
              "repos/$GITHUB_REPOSITORY/pulls/$PR"
          )"
          state="$(jq --raw-output .state <<< "$pr_data")"
          merged="$(jq --raw-output .merged <<< "$pr_data")"
          automerge_enabled="$(jq --raw-output '.auto_merge != null' <<< "$pr_data")"
          if [[ -z "$state" ]] ||
             [[ -z "$merged" ]] ||
             [[ -z "$automerge_enabled" ]]
          then
            echo "::error ::Failed to get PR data!"
            exit 1
          fi
          if [[ "$state" == "closed" ]]; then
            echo "::error ::PR #$PR is closed!"
            exit 1
          fi
          requires_merge=true
          if [[ "$merged" == "true" || "$automerge_enabled" == "true" ]]; then
            echo '::notice ::Pull request is either already merged or queued to merge.'
            requires_merge=false
          fi
          if [[ "$requires_merge" == "true" ]]; then
            gh pr comment "$PR" --body "Auto-approving repo owner PR" --repo "$GITHUB_REPOSITORY"
            gh pr review --approve "$PR" --repo "$GITHUB_REPOSITORY"
          fi
  trigger_artifact_test:
    needs: [setup-matrix, test-bot, autoreview-check]
    runs-on: ubuntu-latest
    steps:
      - name: Trigger artifact CI test workflow
        if: ${{ success() && format('{0}', needs.autoreview-check.outputs.authorized) == 'true' }}
        uses: actions/github-script@v7
        env:
          DISPATCH_REF: "${{ needs.setup-matrix.outputs.dispatch_ref }}"
          RUNNER_TEMP: "${{ runner.temp }}"
        with:
          script: |
            const fs = require('node:fs');
            const osList = ${{ needs.setup-matrix.outputs.os_list }};
            const outputs = ${{ toJson(needs.test-bot.outputs) }};
            const dispatchRef = process.env.DISPATCH_REF || 'master';
            console.log('osList:', osList);
            console.log('test-bot outputs:', outputs);

            let artifactData = {};
            for (const os of osList) {
              const key = `artifact_${os}`;
              try {
                if (outputs[key]) {
                  artifactData[os] = JSON.parse(outputs[key]);
                  core.notice(`\u001b[1m\u001b[38;5;6mArtifact:\u001b[0m \u001b[38;5;2m${os}\u001b[0m => ${outputs[key]}`);
                }
              } catch (e) {
                core.warning(`\u001b[1m\u001b[38;5;3mWarning:\u001b[0m Failed to parse artifact data for \u001b[38;5;4m${os}\u001b[0m: \u001b[38;5;9m${e.message}\u001b[0m`);
              }
            }
            console.log('artifactData:', artifactData);
            core.summary.addDetails('Bottles Artifact Data:', `<pre lang="javascript"><code>${JSON.stringify(artifactData)}</code></pre>`);
            const bottles_metadata_dir = core.toPlatformPath(`${process.env.RUNNER_TEMP}/bottles-artifact`);
            const bottles_metadata_file = core.toPlatformPath(`${bottles_metadata_dir}/bottles-metadata.json`);
            try {
              io.mkdirP(bottles_metadata_dir);
              fs.writeFileSync(bottles_metadata_file, JSON.stringify(artifactData));
              console.log(`Wrote ${bottles_metadata_file}`);
            } catch (err) {
              console.error(err);
              core.error(`\u001b[1m\u001b[38;5;1mError:\u001b[0m Failed to write \u001b[38;5;6m${bottles_metadata_file}\u001b[0m: \u001b[38;5;9m${err.message}\u001b[0m`);
            }
            await github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'ci.yml',
              ref: dispatchRef,
              inputs: {
                bottles_artifact_data: JSON.stringify(artifactData)
              }
            });
          result-encoding: string
      - name: Upload bottles-metadata.json as artifact
        id: upload-bottles-metadata
        if: ${{ success() && format('{0}', needs.autoreview-check.outputs.authorized) == 'true' }}
        uses: actions/upload-artifact@v4
        with:
          name: bottles-metadata.json
          path: '${{ runner.temp }}/bottles-artifact/bottles-metadata.json'
